"use client";

import { useState } from "react";
import { AiSummary, summarizeManifest } from "../lib/api";
import { SparkIcon } from "./icons";

export function AiPanel({ name, content }: { name: string; content: string }) {
  const [summary, setSummary] = useState<AiSummary | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      setSummary(await summarizeManifest(name, content));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not generate summary");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="ai-panel">
      <div className="ai-head">
        <div className="ai-title">
          <SparkIcon className="icon-sm" />
          <div>
            <h3>Assistant</h3>
            <p>Plain-language readiness summary and prioritized fixes.</p>
          </div>
        </div>
        <button className="ghost-button" onClick={generate} disabled={loading}>
          {loading ? "Working…" : summary ? "Regenerate" : "Generate"}
        </button>
      </div>

      {error && <div className="error-inline">{error}</div>}

      {summary ? (
        <div className="ai-body">
          <div className="ai-headline">{summary.headline}</div>
          <p className="ai-summary">{summary.executive_summary}</p>
          <div className="ai-readiness">{summary.readiness}</div>
          {summary.prioritized_fixes.length > 0 && (
            <ol className="ai-fixes">
              {summary.prioritized_fixes.map((fix, index) => (
                <li key={index}>{fix}</li>
              ))}
            </ol>
          )}
          <div className="ai-provider">
            {summary.ai_enabled ? `Generated by ${summary.provider}` : "Deterministic output · set AI_PROVIDER to enable model-written summaries"}
          </div>
        </div>
      ) : (
        <p className="ai-hint">
          Works offline by default. With <code>AI_PROVIDER</code> configured it routes the same analysis through a model for
          narrative explanations.
        </p>
      )}
    </div>
  );
}
